# This file contains values from Cookiecutter

default_context:
  project_name: "AdverX"
  repo_name: "AdverX"
  description: "Official repository for AdverX-Ray."
  organization: "TUe"
  license: "No license"
  organization_email: "none@none.pt"
  line_length: "120"
  python_minimal_version: "3.10"
