site_name: AdverX
site_description: Official repository for AdverX.
site_author: Francisco Caetano

#repo_url:

theme:
    name: 'material'
    locale: en
    font: false

nav:
    - Home: index.md

# WIP
#markdown_extensions:
#  - mkautodoc
#plugins:
#  - mkdocs-jupyter
