wandb_version: 1

batch_size:
  desc: null
  value: 32
n_epochs:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.0002
latent_dim:
  desc: null
  value: 128
hidden_dims:
  desc: null
  value:
  - 16
  - 32
  - 64
  - 128
  - 256
num_samples:
  desc: null
  value: 16
gen_weight:
  desc: null
  value: 0.002
recon_weight:
  desc: null
  value: 0.002
sample_and_save_frequency:
  desc: null
  value: 5
outlier_detection:
  desc: null
  value: false
kld_weight:
  desc: null
  value: 0.0001
loss_type:
  desc: null
  value: mse
patches_image:
  desc: null
  value: 8
split:
  desc: null
  value: 0.7
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720013638
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.14
      5: 0.17.3
      8:
      - 3
      - 5
      13: windows-amd64
